### ISSUE TITLE
Improve docstrings in functions 

### ISSUE THREAD

**Issue by lee-t** [Caochris/SCOTIA#4]
Rewrite docstrings to include executable examples. This will allow for [doctests](https://docs.python.org/3/library/doctest.html) in addition to improving documentation.

**Comment by lgeistlinger** [comment]
see eg the docstrings here for some good examples: https://github.com/ccb-hms/BioPlexPy

**Comment by lgeistlinger** [comment]
The documentation of each function within the codebase should contain:

- [] Title
- [] Short description
- [] Inputs (@params) (incl. data type and short description)
- [] Outputs (@returns) (incl. data type and short description)
- [] An executable example that illustrates how to use the function

**Comment by Caochris** [comment]
Thanks, I have added annotations.
