### ISSUE TITLE
Short description of method

### ISSUE THREAD

**Issue by lgeistlinger** [Caochris/SCOTIA#9]
It would be helpful to provide a three-sentence summary paragraph of the method right in the beginning of the README. 

Currently it says:

"Scotia is a Python package for inferring ligand–receptor interactions from spatial imaging data."

This could be expanded. 

Eg:

"Spatially Constrained Optimal Transport Interaction Analysis (SCOTIA) is a Python package for inferring cell-cell interactions from imaging-based spatial omics data. The main idea of the method is to use an optimal transport model with a cost function that includes both spatial distance and ligand–receptor gene expression. The three key steps of the method are: (1) spatial clustering to identify adjacent source and target cluster pairs, (2) scoring of candidate cell-cell interactions by solving an optimal transport problem between spatially proximal source and target cluster, and (3) significance assessment of the resulting spatially-constrained cell-cell interaction scores through permutation."

Also linking to the [preprint](https://www.biorxiv.org/content/10.1101/2023.06.28.546848v1) at the end of the summary paragraph would be helpful for anyone wanting to reading up on the details.

**Comment by Caochris** [comment]
Thanks for your suggestions! I added the description and citation.
